-- Demo seed data — 3 example forecasts (1 light, 2 deep)
-- Run once against your Supabase project to populate demo runs
-- psql $DATABASE_URL -f supabase/seed.sql

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. LIGHT — Will GTA VI actually release in 2026?
-- ─────────────────────────────────────────────────────────────────────────────

with gta as (
  insert into forecasts (id, topic, horizon, content, created_at)
  values (
    'a1b2c3d4-0001-0001-0001-000000000001',
    'Will GTA VI actually release in 2026?',
    '6 months',
    $content$
## Current State Assessment

Rockstar Games confirmed a fall 2025 release window for GTA VI in May 2024, then quietly shifted guidance to 2026 in a Take-Two Interactive earnings call. As of April 2026, no revised release date has been publicly announced. Take-Two's fiscal year ends March 31 — GTA VI remains the single largest catalyst on their balance sheet, with analyst estimates placing opening-year revenue above $3B. The game was officially revealed via trailer in December 2023; a second trailer has not been released. No marketing cadence typically associated with a 90-day launch window (retailer listings, rating filings, pre-order launches) has materialized as of this forecast.

## Key Predictions

- **72%** GTA VI releases on a major platform before December 31, 2026 — Take-Two's fiscal pressure and the absence of further delay signals make a 2026 launch still most likely
- **55%** A firm release date is announced within the next 8 weeks — typical Rockstar marketing cadence places announcement 90–120 days before launch
- **38%** GTA VI launches before September 2026 — a summer window is possible but aggressive given no date is confirmed
- **21%** GTA VI slips to 2027 — triggered only if Take-Two issues a material guidance revision in the next earnings call
- **85%** If released in 2026, it breaks first-week global sales records — no meaningful open-world AAA competition exists in the same window

## Bottom Line

GTA VI will most likely release in fall 2026 — but the absence of a second trailer or a confirmed date by April keeps material delay risk alive at roughly 1-in-5 odds. The single variable to watch: Take-Two's next earnings call and whether any marketing cadence shift follows within 2 weeks.
    $content$,
    '2026-04-01 09:00:00+00'
  )
  returning id
)
insert into prediction_runs (forecast_id, topic, horizon, mode, predictions, status, created_at)
select
  id,
  'Will GTA VI actually release in 2026?',
  '6 months',
  'light',
  '[
    {"prediction_text": "GTA VI releases on a major platform before December 31, 2026", "confidence": 72, "timeframe": null, "resolution_criteria": null},
    {"prediction_text": "A firm release date is announced within the next 8 weeks", "confidence": 55, "timeframe": null, "resolution_criteria": null},
    {"prediction_text": "GTA VI launches before September 2026", "confidence": 38, "timeframe": null, "resolution_criteria": null},
    {"prediction_text": "GTA VI slips to 2027", "confidence": 21, "timeframe": null, "resolution_criteria": null},
    {"prediction_text": "If released in 2026, it breaks first-week global sales records", "confidence": 85, "timeframe": null, "resolution_criteria": null}
  ]'::jsonb,
  'pending',
  '2026-04-01 09:00:00+00'
from gta;


-- ─────────────────────────────────────────────────────────────────────────────
-- 2. DEEP — Will AI-generated music dominate the Billboard Hot 100?
-- ─────────────────────────────────────────────────────────────────────────────

with aimusic as (
  insert into forecasts (id, topic, horizon, content, created_at)
  values (
    'a1b2c3d4-0002-0002-0002-000000000002',
    'Will AI-generated music dominate the Billboard Hot 100?',
    '3 years',
    $content$
## Current State Assessment

As of Q1 2026, AI-assisted music production is mainstream — nearly every major label uses AI tools for mixing, mastering, and stem separation. Fully AI-generated tracks (no human performer credited) have charted in the lower Hot 100 three times, most recently an anonymous electronic track in February 2026 reaching #67. Billboard updated its eligibility rules in late 2025 to require at least one credited human creative contributor, effectively barring pure AI tracks from official charts. The RIAA reported that 23% of music released on streaming platforms in 2025 was predominantly AI-generated by volume, though only 4% by stream count. Suno and Udio report combined active users exceeding 8 million monthly.

## Base Rate Analysis

Base rate: 5% — historically, paradigm-shifting formats (rap, EDM, K-pop) have required 8–15 years to reach chart dominance from niche origin. AI music is at approximately year 3 of meaningful public presence.

[+12%] AI tool quality is improving faster than historical genre adoption curves — Suno, Udio, and proprietary label tools already produce radio-quality output (epistemic)
[+8%] Streaming economics heavily favor volume; AI has near-zero marginal cost per track (aleatory)
[-10%] Billboard eligibility rules create a structural ceiling on pure-AI chart dominance (epistemic — rules subject to change)
[-7%] Listener preference data shows strong bias toward human artist identity, especially in pop and hip-hop (aleatory)
[-5%] Major labels have financial incentive to suppress AI-origin tracks that cannibalize signed artist revenue (epistemic)
────
Final estimate: ~28% probability AI-generated or AI-primary tracks hold 5+ simultaneous Hot 100 positions within 3 years

Prediction market: 31% (Metaculus, n=412) — close alignment; slight divergence explained by the Metaculus question predating Billboard's 2025 eligibility rule changes.

## Key Drivers & Trends

1. **AI tool accessibility** — barrier to creating chart-quality music dropped from a $50k studio budget to a ~$20/month subscription (highest impact)
2. **Streaming volume economics** — platform algorithms favor engagement metrics, not human origin; AI can generate infinite variations optimized for retention
3. **Label hedge strategy** — major labels are investing in AI subsidiaries while lobbying for restrictive chart rules simultaneously — a hedge, not a hard block
4. **Listener identity and parasocial attachment** — fandom and parasocial connection remain deeply human; AI lacks the celebrity engine that drives sustained chart performance
5. **Regulatory and platform rules** — Billboard eligibility, Grammy standards, and DSP disclosure requirements are the primary structural constraints for the next 3 years

## Scenario Analysis

**Optimistic — AI Breaks Through (30%)**
Billboard softens eligibility rules under pressure from indie labels and streaming platforms → AI-primary tracks become chart-eligible → low-cost viral AI tracks optimized for TikTok hooks flood the Hot 100 lower half → by 2028, 10–15 positions routinely held by AI-primary tracks.
Rule change unlocks eligibility → volume advantage converts directly to chart presence → listener habituation follows exposure.

**Base Case — Hybrid Dominance (52%)**
AI remains a production tool credited to human artists. Every top-10 hit uses significant AI in production, but credited performers remain human. No track labeled "AI-generated" dominates — instead the line blurs until the distinction becomes commercially meaningless. The Hot 100 looks human-dominated on paper; in practice, AI wrote half the melody and mastered the final mix.

**Pessimistic — Backlash Containment (18%)**
Public backlash to AI music intensifies following a high-profile scandal — a faked AI voice of a deceased artist, or a major streaming fraud case. Platforms introduce mandatory AI disclosure. Listener sentiment hardens. AI music gets quarantined to genre-specific charts. The Hot 100 remains effectively human-only through 2029.

## Predictions Table

| Timeframe | Prediction | Confidence | Key Assumption | Resolved When |
|-----------|------------|------------|----------------|---------------|
| 12 months | An AI-primary track (with disclosed AI origin) cracks Hot 100 top 50 | 41% | Billboard eligibility rules loosen or are worked around via nominal human co-credit | Billboard chart archives show an AI-disclosed track at position ≤50 |
| 18 months | A major label officially releases and markets an AI-generated album under a non-human brand identity | 63% | Labels conclude AI branding is commercially viable in at least one genre (electronic or ambient) | Major label press release or RIAA registration of an AI-origin album with explicit non-human branding |
| 3 years | AI-generated or AI-primary tracks hold 5 or more simultaneous Hot 100 positions | 28% | Chart rules change OR the human co-credit workaround becomes a recognized industry standard | Any single weekly Hot 100 chart shows 5+ tracks with disclosed AI-primary origin |
| 3 years | The Grammy Awards creates an official AI music category | 57% | NARAS responds to lobbying pressure from both labels and AI music advocates | Official Grammy category announcement published by the Recording Academy |

## Wild Cards

- **AI voice clone of a living superstar goes viral without consent (18%)** — triggers emergency platform crackdowns and federal legislation, effectively banning undisclosed AI music from all major DSPs
- **A fully AI "artist" with a fabricated persona reaches 10M monthly Spotify listeners (35%)** — normalizes AI artists as legitimate chart contenders, accelerates Billboard rule reassessment
- **Streaming platforms introduce an AI-origin filter letting users exclude AI music (45%)** — bifurcates the market; AI music thrives in its own ecosystem but never crosses into Hot 100 mainstream

## Steelman

The strongest case that AI music does not dominate in 3 years: music consumption is fundamentally parasocial. People do not just stream songs — they follow artists, attend concerts, watch interviews, and build identity around fandom. AI has no face, no backstory, no beef, no heartbreak. The entire promotional infrastructure of the music industry — press, social media, touring, brand deals — requires a human anchor. The Hot 100 is not a pure meritocracy of sonic quality; it is a reflection of cultural attention. Until AI can manufacture cultural presence — not just audio — it will remain a production tool, not a chart contender.

## Pre-Mortem

The most likely single cause of this forecast missing: Billboard changes its eligibility definition in response to label lobbying in a direction that *further restricts* AI participation rather than liberalizes it. If the Recording Academy and major DSPs align on a stricter "meaningful human authorship" standard with legal backing, the structural ceiling becomes a floor, and the 28% base scenario probability collapses to near zero within 18 months.

## Conclusion

Most likely outcome: AI becomes invisible infrastructure in music production — credited to humans, powering most of what you hear, but never "dominating" the Hot 100 in a way that is legible on the chart surface. The hybrid scenario (52%) is the one to bet on through 2029.

Most important variable to watch: Billboard's next eligibility rule revision, scheduled for review in Q3 2026. The direction of that ruling sets the ceiling for the following 3 years.

Sensitivity statement: If Billboard liberalizes eligibility from "human contributor required" to "human curator required," probability of 5+ simultaneous Hot 100 AI positions shifts from 28% to approximately 55%.

Invalidation condition: A cross-platform agreement explicitly barring AI-disclosed tracks from all major chart eligibility before end of 2026 would collapse the optimistic scenario below 10% and force a full recalibration around the hybrid/pessimistic split.
    $content$,
    '2026-04-01 10:30:00+00'
  )
  returning id
)
insert into prediction_runs (forecast_id, topic, horizon, mode, predictions, status, created_at)
select
  id,
  'Will AI-generated music dominate the Billboard Hot 100?',
  '3 years',
  'deep',
  '[
    {"prediction_text": "An AI-primary track (with disclosed AI origin) cracks Hot 100 top 50", "confidence": 41, "timeframe": "12 months", "resolution_criteria": "Billboard eligibility rules loosen or are worked around via nominal human co-credit"},
    {"prediction_text": "A major label officially releases and markets an AI-generated album under a non-human brand identity", "confidence": 63, "timeframe": "18 months", "resolution_criteria": "Labels conclude AI branding is commercially viable in at least one genre"},
    {"prediction_text": "AI-generated or AI-primary tracks hold 5 or more simultaneous Hot 100 positions", "confidence": 28, "timeframe": "3 years", "resolution_criteria": "Chart rules change OR human co-credit workaround becomes industry standard"},
    {"prediction_text": "The Grammy Awards creates an official AI music category", "confidence": 57, "timeframe": "3 years", "resolution_criteria": "NARAS responds to lobbying from labels and AI music advocates"}
  ]'::jsonb,
  'pending',
  '2026-04-01 10:30:00+00'
from aimusic;


-- ─────────────────────────────────────────────────────────────────────────────
-- 3. DEEP — Will AI replace most software engineering jobs?
-- ─────────────────────────────────────────────────────────────────────────────

with aijobs as (
  insert into forecasts (id, topic, horizon, content, created_at)
  values (
    'a1b2c3d4-0003-0003-0003-000000000003',
    'Will AI replace most software engineering jobs?',
    '5 years',
    $content$
## Current State Assessment

As of Q1 2026, AI coding tools (GitHub Copilot, Cursor, Claude Code, and similar) are used by an estimated 62% of professional software engineers. Layoffs in the technology sector accelerated through 2025, with major firms citing AI productivity gains as a contributing factor alongside macro conditions — though isolating AI's causal contribution remains contested. The Bureau of Labor Statistics projects software developer employment growing 17% through 2030 in its 2024 outlook, while a competing McKinsey analysis estimates 45% of current software engineering tasks are automatable with existing AI as of 2025. The gap between "tasks automatable" and "jobs eliminated" is the central uncertainty in this forecast.

## Base Rate Analysis

Base rate: 8% — historical automation waves (manufacturing, data entry, basic legal research) eliminated specific task clusters but rarely entire professions within a 5-year window. The accounting and radiology precedents suggest AI handles sub-tasks while human roles restructure around higher-order judgment.

[+18%] Current AI coding capabilities already handle full feature implementation end-to-end for well-specified problems — qualitatively different from prior automation (epistemic)
[+10%] Economic incentive is unusually strong: median US software engineer salary is $130k; replacing even 30% of output with AI has massive ROI (aleatory)
[-15%] "Most jobs" requires >50% employment reduction — no automation wave has achieved this in a 5-year window in a white-collar profession (aleatory)
[-8%] Software complexity and requirements ambiguity continue to expand the scope of what engineers are asked to do — Jevons paradox applies (epistemic)
[-6%] Organizational inertia, security reviews, and compliance requirements slow AI adoption in enterprise contexts (epistemic)
────
Final estimate: ~12% probability that software engineering employment falls by more than 50% within 5 years

Prediction market: 9% (Metaculus, n=1,847) — model estimate slightly higher; divergence explained by this forecast weighting recent capability acceleration more heavily than the Metaculus crowd, which includes many software engineers with professional skepticism bias.

## Key Drivers & Trends

1. **AI coding capability trajectory** — the gap between "AI can write code" and "AI can own a codebase" is narrowing faster than most 2023 predictions anticipated (highest impact)
2. **Task vs. job distinction** — automating 70% of tasks does not eliminate the role; it restructures it toward architecture, requirements, and review — which are harder to automate
3. **Demand elasticity** — cheaper software production historically expanded total software demand; the same dynamic may absorb productivity gains into more software, not fewer engineers
4. **Enterprise adoption lag** — Fortune 500 procurement, security review, and change management cycles mean AI capability in 2026 becomes enterprise standard in 2028–2029
5. **Junior pipeline collapse** — the most observable near-term effect: junior hiring freezes as AI handles entry-level tasks, shrinking the pipeline of future senior engineers

## Scenario Analysis

**Optimistic for AI — Structural Displacement (12%)**
AI agents become reliable enough to own full development cycles for well-scoped projects by 2027 → companies restructure engineering orgs from 100-person teams to 10-person AI-oversight teams → software engineer employment falls 40–60% by 2031. Productivity gains do not generate proportional new demand because software is already abundant.
Capability threshold crossed → economic incentive drives rapid restructuring → employment contracts faster than new roles absorb displaced workers.

**Base Case — Restructuring Without Replacement (68%)**
AI handles 50–70% of coding tasks by 2028, but total employment remains within 20% of 2026 levels. Engineers shift toward architecture, product reasoning, AI supervision, and security. Junior hiring freezes; senior demand holds. The profession looks different — smaller teams, higher individual leverage — but has not been "replaced."

**Pessimistic for AI — Plateau and Integration (20%)**
AI coding tools plateau in capability around current levels for 2–3 years due to context window limits, hallucination in large codebases, and enterprise trust deficits. Adoption slows. Engineering employment continues growing per BLS projections. AI becomes a productivity multiplier comparable to IDEs or Stack Overflow — important but not transformative at the job level.

## Predictions Table

| Timeframe | Prediction | Confidence | Key Assumption | Resolved When |
|-----------|------------|------------|----------------|---------------|
| 2 years | Junior software engineer hiring falls more than 40% industry-wide vs. 2024 levels | 61% | AI handles entry-level task scope reliably enough that companies freeze junior pipelines | BLS or LinkedIn Workforce Report shows >40% YoY decline in junior SWE job postings |
| 3 years | At least 3 Fortune 500 companies publicly report reducing engineering headcount by 30%+ citing AI productivity | 44% | Companies are willing to publicly attribute headcount reduction to AI (reputation risk may suppress disclosure) | SEC filing, earnings call transcript, or verified press release from 3+ Fortune 500 firms |
| 5 years | Total US software engineer employment is more than 20% below 2026 levels | 19% | Demand elasticity fails to absorb productivity gains; no major new software category emerges | BLS Occupational Employment Statistics report for 2031 |
| 5 years | A new job category ("AI systems engineer" or equivalent) appears in BLS standard occupational classification | 71% | Role restructuring generates enough distinct employment to warrant formal classification | BLS SOC revision includes a distinct AI engineering or AI supervision category |

## Wild Cards

- **An AI agent autonomously ships a production feature at a major tech company with zero human code review (52%)** — becomes a celebrated case study that accelerates enterprise trust and org restructuring timelines by 2–3 years
- **A high-profile AI coding failure causes a major outage or security breach attributed to AI-generated code (41%)** — triggers industry-wide pullback, mandatory human review requirements, and a 12–18 month slowdown in enterprise AI adoption
- **Governments mandate "human in the loop" requirements for software in critical infrastructure (28%)** — creates a protected employment floor for senior engineers in finance, healthcare, and government sectors

## Steelman

The strongest case that software engineers are not largely replaced in 5 years: software is not a solved problem. The more AI lowers the cost of writing code, the more software gets written, the more complex systems become, and the more there is to maintain, secure, and reason about. Every layer of abstraction in software history — from assembly to C to managed languages to cloud infrastructure — was supposed to reduce programmer demand. Each one expanded it. AI is likely the next layer, not the last one. The engineers who understand what AI-generated code is actually doing will be more valuable, not less.

## Pre-Mortem

The most likely single cause of this forecast missing on the optimistic side: AI agents crack the context problem — maintaining coherent understanding of large, legacy codebases with ambiguous requirements — before 2028. Current AI coding failures cluster heavily around this limitation. If a model demonstrates reliable full-codebase reasoning on a 500k+ line enterprise system, the restructuring timeline compresses significantly and the 12% displacement scenario probability roughly doubles.

## Conclusion

Most likely outcome: software engineering restructures rather than contracts. Total employment stays within 20% of 2026 levels by 2031, but the shape of the profession changes — smaller teams, frozen junior pipelines, higher individual leverage, and growing demand for engineers who can direct and audit AI systems rather than write code from scratch.

Most important variable to watch: junior hiring data in Q3 2026. If major tech companies confirm junior freeze policies in earnings calls, the restructuring scenario is confirmed and the timeline for senior role changes moves forward.

Sensitivity statement: If AI agents demonstrate reliable full-codebase reasoning on enterprise-scale systems before 2028 (currently the primary capability gap), probability of >20% employment decline shifts from 19% to approximately 38%.

Invalidation condition: If US software engineer employment grows more than 10% above 2026 levels by 2029, the displacement thesis is falsified and the demand elasticity (Jevons) scenario becomes dominant.
    $content$,
    '2026-04-01 11:45:00+00'
  )
  returning id
)
insert into prediction_runs (forecast_id, topic, horizon, mode, predictions, status, created_at)
select
  id,
  'Will AI replace most software engineering jobs?',
  '5 years',
  'deep',
  '[
    {"prediction_text": "Junior software engineer hiring falls more than 40% industry-wide vs. 2024 levels", "confidence": 61, "timeframe": "2 years", "resolution_criteria": "AI handles entry-level task scope reliably enough that companies freeze junior pipelines"},
    {"prediction_text": "At least 3 Fortune 500 companies publicly report reducing engineering headcount by 30%+ citing AI productivity", "confidence": 44, "timeframe": "3 years", "resolution_criteria": "Companies willing to publicly attribute headcount reduction to AI"},
    {"prediction_text": "Total US software engineer employment is more than 20% below 2026 levels", "confidence": 19, "timeframe": "5 years", "resolution_criteria": "Demand elasticity fails to absorb productivity gains"},
    {"prediction_text": "A new job category (AI systems engineer or equivalent) appears in BLS standard occupational classification", "confidence": 71, "timeframe": "5 years", "resolution_criteria": "Role restructuring generates enough distinct employment to warrant formal BLS classification"}
  ]'::jsonb,
  'pending',
  '2026-04-01 11:45:00+00'
from aijobs;
