import { supabase } from '@/lib/supabase'
import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import Link from 'next/link'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'

type Props = { params: Promise<{ id: string }> }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params
  const { data } = await supabase
    .from('forecasts')
    .select('topic, horizon, content')
    .eq('id', id)
    .single()

  if (!data) return { title: 'Forecast — OpenFuture' }

  const bottomLine = extractBottomLine(data.content)

  return {
    title: `${data.topic} (${data.horizon}) — OpenFuture`,
    description: bottomLine ?? `AI forecast for ${data.topic} over ${data.horizon}`,
    openGraph: {
      title: `${data.topic} // ${data.horizon.toUpperCase()}`,
      description: bottomLine ?? `AI-powered forecast by OpenFuture`,
      siteName: 'OpenFuture',
    },
    twitter: {
      card: 'summary',
      title: `${data.topic} // ${data.horizon.toUpperCase()}`,
      description: bottomLine ?? `AI-powered forecast by OpenFuture`,
    },
  }
}

function extractBottomLine(content: string): string | null {
  const match = content.match(/##\s*Bottom Line\s*\n([\s\S]*?)(?=\n##|$)/)
  if (!match) return null
  return match[1].replace(/[*_#`▌▶█]/g, '').trim().slice(0, 280)
}

export default async function ForecastPage({ params }: Props) {
  const { id } = await params
  const { data: forecast } = await supabase
    .from('forecasts')
    .select('id, topic, horizon, content, created_at')
    .eq('id', id)
    .single()

  if (!forecast) notFound()

  const bottomLine = extractBottomLine(forecast.content)
  const date = new Date(forecast.created_at).toISOString().replace('T', ' ').slice(0, 16) + ' UTC'

  return (
    <main className="mx-auto w-full max-w-4xl px-4 py-10 space-y-4">

      {/* Header */}
      <div
        className="border px-5 py-4"
        style={{ borderColor: 'var(--green-border)', background: 'var(--bg-panel)' }}
      >
        <div className="flex items-start justify-between gap-4 flex-wrap">
          <div>
            <p className="text-xs tracking-widest mb-1" style={{ color: 'var(--green-muted)' }}>
              ── ORACLE ENGINE // FORECAST REPORT ──
            </p>
            <h1
              className="text-xl font-bold uppercase tracking-wide"
              style={{ color: 'var(--green-bright)' }}
            >
              {forecast.topic}
            </h1>
            <div className="flex items-center gap-3 mt-2">
              <span
                className="text-xs tracking-widest uppercase border px-2 py-0.5"
                style={{ borderColor: 'var(--green-border)', color: 'var(--green-muted)' }}
              >
                {forecast.horizon.toUpperCase()}
              </span>
              <span className="text-xs" style={{ color: 'var(--green-faint)' }}>
                {date}
              </span>
            </div>
          </div>
          <Link
            href="/"
            className="text-xs tracking-widest uppercase border px-4 py-2 transition-all hover:bg-[var(--green-faint)] shrink-0"
            style={{ borderColor: 'var(--green-border)', color: 'var(--green-muted)' }}
          >
            [RUN YOUR OWN]
          </Link>
        </div>
      </div>

      {/* Bottom Line card */}
      {bottomLine && (
        <div
          className="border-l-2 px-5 py-4"
          style={{ borderColor: 'var(--green-dim)', background: 'var(--bg-panel)' }}
        >
          <p className="text-xs tracking-widest uppercase mb-2" style={{ color: 'var(--green-muted)' }}>
            ▶ BOTTOM LINE
          </p>
          <p className="text-sm leading-relaxed" style={{ color: 'var(--green)' }}>
            {bottomLine}
          </p>
        </div>
      )}

      {/* Full forecast */}
      <div
        className="border px-6 py-6"
        style={{ borderColor: 'var(--green-border)', background: 'var(--bg-panel)' }}
      >
        <div className="terminal-md text-sm leading-relaxed">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{forecast.content}</ReactMarkdown>
        </div>
      </div>

      {/* Footer CTA */}
      <div
        className="border px-5 py-4 flex items-center justify-between"
        style={{ borderColor: 'var(--green-border)' }}
      >
        <p className="text-xs tracking-widest" style={{ color: 'var(--green-faint)' }}>
          GENERATED BY OPENFUTURE // ORACLE ENGINE
        </p>
        <Link
          href="/"
          className="text-xs tracking-widest uppercase border px-4 py-2 transition-all hover:bg-[var(--green-faint)]"
          style={{ borderColor: 'var(--green-border)', color: 'var(--green-muted)' }}
        >
          [NEW FORECAST]
        </Link>
      </div>

    </main>
  )
}
